import {  Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";


const outfit = Outfit({
  subsets: ["latin"]
})



export const metadata = {
  title: "Pixgen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`${outfit.className} light h-full antialiased`}
    >
      <body className="min-h-full bg-background text-foreground flex flex-col">
        <Navbar />
        <main className="container mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
